# Generated by Django 4.2.13 on 2024-06-01 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_cylinder_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='delivery_person',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('is_delivery', True)), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL),
        ),
    ]
