# Generated by Django 4.2.13 on 2024-06-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Assigned', 'Assigned'), ('In_Transit', 'In_Transit'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
